/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neolix_neolixcubing_NeolixCubing */

#ifndef _Included_com_neolix_neolixcubing_NeolixCubing
#define _Included_com_neolix_neolixcubing_NeolixCubing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neolix_neolixcubing_NeolixCubing
 * Method:    connectCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_neolix_neolixcubing_NeolixCubing_connectCamera
  (JNIEnv *, jclass);

/*
 * Class:     com_neolix_neolixcubing_NeolixCubing
 * Method:    disconnectCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_neolix_neolixcubing_NeolixCubing_disconnectCamera
  (JNIEnv *, jclass);

/*
 * Class:     com_neolix_neolixcubing_NeolixCubing
 * Method:    getCurrentVolume
 * Signature: (Lcom/neolix/neolixcubing/Volume;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_neolix_neolixcubing_NeolixCubing_getCurrentVolume
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_neolix_neolixcubing_NeolixCubing
 * Method:    setUseCase
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_neolix_neolixcubing_NeolixCubing_setUseCase
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_neolix_neolixcubing_NeolixCubing
 * Method:    SetSafeArea
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_neolix_neolixcubing_NeolixCubing_SetSafeArea
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_neolix_neolixcubing_NeolixCubing
 * Method:    SetMeasureArea
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_neolix_neolixcubing_NeolixCubing_SetMeasureArea
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
